### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Vishalini03** [sumitkumar1503/bloodbankmanagement#8]
can't able create a user id with password authentication in 'py create user' command in terminal

**Comment by Punit-99** [comment]
The password is invisible just hit enter when you done entering password

**Comment by Punit-99** [comment]
> 

can't able create a user id with password authentication in 'py create user' command in terminal

**Comment by Punit-99** [comment]
> can't able create a user id with password authentication in 'py create user' command in terminal

The password is invisible just hit enter when you re done entering password
